# Generated by Django 5.0.4 on 2024-04-04 20:27

import ckeditor.fields
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя_боса')),
                ('image_boss', models.ImageField(upload_to='image_boss/', verbose_name='Фото боса')),
                ('about_boss', ckeditor.fields.RichTextField(verbose_name='Информация про боса')),
            ],
            options={
                'verbose_name': 'Босс',
                'verbose_name_plural': 'Босс',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('image1', models.ImageField(upload_to='image1/', verbose_name='Фотографии')),
                ('image2', models.ImageField(upload_to='image2/', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Условие ',
                'verbose_name_plural': 'Условия',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_gallery', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_one', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='price/', verbose_name='Первая фотография')),
                ('image_two', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='price/', verbose_name='Первая фотография')),
                ('image', models.ImageField(upload_to='image', verbose_name='Фото Граунд')),
            ],
            options={
                'verbose_name': 'Прайс',
                'verbose_name_plural': 'Прайс',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Фотография')),
                ('descriptions1', ckeditor.fields.RichTextField(verbose_name='Описание1')),
                ('letter', models.TextField(verbose_name='Письмо текст')),
                ('descriptions2', ckeditor.fields.RichTextField(verbose_name='Описание1')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_team/', verbose_name='Фото мемберов')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='TeamAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_team/', verbose_name='Фото Команды')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('work', models.CharField(max_length=255, verbose_name='Должность')),
                ('instagram', models.URLField(verbose_name='Инстаграм')),
                ('twitter', models.URLField(verbose_name='Вотсап')),
                ('facebook', models.URLField(verbose_name='Фейсбук')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Члены команды',
            },
        ),
        migrations.CreateModel(
            name='Usluga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название_услуги')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Описание_услуги')),
                ('image', models.ImageField(upload_to='image_usluga', verbose_name='Фотграфия_услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
