# Generated by Django 5.0.4 on 2024-04-04 20:27

import ckeditor.fields
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name=' Название')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('logo', models.ImageField(upload_to='logo_image', verbose_name='Логотип')),
                ('locations', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('instagram', models.URLField(verbose_name='Инстаграм')),
                ('twitter', models.URLField(verbose_name='Вотсап')),
                ('facebook', models.URLField(verbose_name='Фейсбук')),
            ],
            options={
                'verbose_name': 'Основная настройка',
                'verbose_name_plural': 'Основные настройки',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='slide/', verbose_name='Фотография')),
                ('title', ckeditor.fields.RichTextField(verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Слайд на главной странице',
                'verbose_name_plural': 'Слайды на главной странице',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='video/', verbose_name='Фотография для баннера')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название видео')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Видео о MerriGarden',
                'verbose_name_plural': 'Видео о MerriGarden',
            },
        ),
    ]
